// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXfxSrO6xNgKImv5Qey9ssy3nO1ZPpuhU',
    appId: '1:501503666844:web:236b9f64de0be618171b59',
    messagingSenderId: '501503666844',
    projectId: 'liveasyinternship-f46c1',
    authDomain: 'liveasyinternship-f46c1.firebaseapp.com',
    storageBucket: 'liveasyinternship-f46c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhO0nlXFQBvASeptqie4qefdyfDgE0VWo',
    appId: '1:501503666844:android:b84be3c3a59ddff4171b59',
    messagingSenderId: '501503666844',
    projectId: 'liveasyinternship-f46c1',
    storageBucket: 'liveasyinternship-f46c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL5oniQSfrkmQUMFOqyUI6yuS-IMxagqk',
    appId: '1:501503666844:ios:864f65dd95777a55171b59',
    messagingSenderId: '501503666844',
    projectId: 'liveasyinternship-f46c1',
    storageBucket: 'liveasyinternship-f46c1.appspot.com',
    iosBundleId: 'com.example.liveasyInternship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL5oniQSfrkmQUMFOqyUI6yuS-IMxagqk',
    appId: '1:501503666844:ios:864f65dd95777a55171b59',
    messagingSenderId: '501503666844',
    projectId: 'liveasyinternship-f46c1',
    storageBucket: 'liveasyinternship-f46c1.appspot.com',
    iosBundleId: 'com.example.liveasyInternship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXfxSrO6xNgKImv5Qey9ssy3nO1ZPpuhU',
    appId: '1:501503666844:web:e88f1015d9f644ba171b59',
    messagingSenderId: '501503666844',
    projectId: 'liveasyinternship-f46c1',
    authDomain: 'liveasyinternship-f46c1.firebaseapp.com',
    storageBucket: 'liveasyinternship-f46c1.appspot.com',
  );
}
